# System
export ZSH="$HOME/.oh-my-zsh"
export SSH_KEY_PATH="$HOME/.ssh/rsa_id"

# Vimrc
export MYVIMRC="$HOME/.vimrc"

# Preferred editor and browser
export EDITOR="nvim"
export BROWSER="firefox"

# Paths
export RUBY_GEMS_PATH="$HOME/.local/share/gem/ruby/3.0.0/bin"
export NPM_GLOBAL_PATH="$HOME/.npm-global/bin"

# XDG Config
export XDG_CONFIG_HOME=/home/deep/.config
