# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
##: init direnv (see: https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-initialize-direnv-when-using-instant-prompt)
. $HOME/.asdf/asdf.sh
(( ${+commands[direnv]} )) && emulate zsh -c "$(asdf exec direnv export zsh)"
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
(( ${+commands[direnv]} )) && emulate zsh -c "$(asdf exec direnv hook zsh)"

# Start GNUPG Agent
# gpg-connect-agent updatestartuptty /bye >/dev/null

# Start ssh-agent with keychain
# keychain id_ed25519 --agents ssh --quiet
eval $(keychain --eval --quiet id_ed25519 ~/.ssh/id_ed25519)

# Load Aliases
source $HOME/.aliases

# If you come from bash you might have to change your $PATH.
export CUDA_PATH=/opt/cuda/bin
export PATH=$HOME/bin:$HOME/.local/bin:/bin:/usr/local/bin:$RUBY_GEMS_PATH:$NPM_GLOBAL_PATH:$CUDA_PATH:$PATH

# Android Studio Env Setup
export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

# Path to your oh-my-zsh installation.
export ZSH="/home/deep/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
# POWERLEVEL10K_MODE='nerdfont-complete'
ZSH_THEME="powerlevel10k/powerlevel10k"
ZLE_RPROMPT_INDENT=0
# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Autostart tmux with zsh
# https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/tmux
# ZSH_TMUX_AUTOSTART=true

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
	httpie    # httpie completions
	adb       # adb completions
	archlinux # archlinux completions
	fzf       # fzf completions
	yarn      # yarn completions
	#asdf             # extendable version manager
	tmux # tmux completions
	#eksctl           # eksctl completions
	helm     # helm completions
	minikube # minikube completions
	#fd 			     # find replacement
	aws   # aws completions
	rsync # rsync aliases
	#flutter          # flutter autocompletion
	python # python helpers
	#poetry          # poetry completions
	#catimg          # cat img to terminal
	colored-man-pages # colorize man pages
	common-aliases    # colorize man pages
	copybuffer        # binds ctrl-o to copy currently typed cmd
	docker-compose    # docker-compose aliases
	#django             # django aliases
	autojump   # 'j' command - smart cd
	git        # git alias/completions
	gitfast    # git... but fast
	git-extras # awesome git scripts
	gh         # github cli
	gpg-agent  # enables gpg agent if not running
	#evalcache		   # cache 'eval' commands
	#alias-tips		   # informs you of an alias if one exists
	#copyzshell		   # copy zsh config over ssh
	#taskwarrior        # taskwarrior
	#timewarrior        # timewarrior aliases / completion
	systemd # systemd aliases
	heroku
	urltools     # provides cmds urlencode/urldecode
	web-search   # provides web_search/google cmd
	fancy-ctrl-z # ctrl-z opens/closes vim
	#encode64           # encode/decode64 cmds
	kubectl # kubctl autocompletion
	#keep              # keep cli completions
	zsh-interactive-cd   # interactive tab completion for cd
	zsh-navigation-tools # history (and more) nav tools
	zsh-autosuggestions  # auto suggestions
	#zsh-vim-mode              # must be loaded after syntax hl
	a5r                     # adstakr autocompletions
	pnpm                    # pnpm autocompletions
	zsh-syntax-highlighting # !! must be last - syntx hl
)

source $ZSH/oh-my-zsh.sh

# Key bind for zsh-autosuggestions
bindkey '^ ' autosuggest-accept

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

#export NVM_DIR="$HOME/.nvm"
#[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Hook zoxide to shell
eval "$(zoxide init zsh)"

# Hook direnv into your shell.
# eval "$(asdf exec direnv hook zsh)"

# A shortcut for asdf managed direnv.
direnv() { asdf exec direnv "$@"; }

export PATH="$HOME/.poetry/bin:$PATH"

# tabtab source for packages
# uninstall by removing these lines
[[ -f ~/.config/tabtab/zsh/__tabtab.zsh ]] && . ~/.config/tabtab/zsh/__tabtab.zsh || true

export PNPM_HOME="/home/deep/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"
source "${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/zshrc"
