actions:
  install_vimplug: |
    test -e ~/.vim/autoload/plug.vim || (
      curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      nvim +PlugInstall +qall 
    )
  install_astronvim: |
    test -e ~/.config/nvim/init.lua || (
      mkdir -p ~/.config/nvim
      git clone --depth 1 https://github.com/AstroNvim/AstroNvim ~/.config/nvim
      nvim
    )
config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_ideavimrc:
    src: ideavimrc
    dst: ~/.ideavimrc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  d_latte:
    src: config/latte
    dst: ~/.config/latte
    upignore:
    - '*.lock'
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  f_p10k.zsh:
    src: p10k.zsh
    dst: ~/.p10k.zsh
  d_fusuma:
    src: config/fusuma
    dst: ~/.config/fusuma
  d_astronvim_user:
    src: config/nvim/lua/user
    dst: ~/.config/nvim/lua/user
    actions:
    - install_astronvim
  f_face:
    src: face
    dst: ~/.face
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_aliases:
    src: aliases
    dst: ~/.aliases
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  f_config:
    src: config/i3/config
    dst: ~/.config/i3/config
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
  f_config.yml:
    src: config/lazygit/config.yml
    dst: ~/.config/lazygit/config.yml
  f_config.kdl:
    src: config/zellij/config.kdl
    dst: ~/.config/zellij/config.kdl
  f_config.toml:
    src: config/helix/config.toml
    dst: ~/.config/helix/config.toml
  f_gh_config.yml:
    src: config/gh/config.yml
    dst: ~/.config/gh/config.yml
    chmod: '600'
  d_scripts:
    src: scripts
    dst: ~/scripts
  d_omz_custom:
    src: oh-my-zsh/custom
    dst: ~/.oh-my-zsh/custom
    upignore:
    - plugins
    - themes
  f_tool-versions:
    src: tool-versions
    dst: ~/.tool-versions
profiles:
  manjarog:
    dotfiles:
    - f_bashrc
    - f_zshrc
    - f_vimrc
    - f_ideavimrc
    - f_gitconfig
    - d_latte
    - d_alacritty
    - f_p10k.zsh
    - d_fusuma
    - d_astronvim_user
    - f_face
    - f_zshenv
    - f_aliases
    - d_kitty
    - f_config
    - f_starship.toml
    - f_config.yml
    - f_config.kdl
    - f_config.toml
    - f_gh_config.yml
    - d_scripts
    - d_omz_custom
    - f_tool-versions
  octopi:
    dotfiles:
    - f_bashrc
    - f_zshrc
    - f_vimrc
    - f_gitconfig
    - f_p10k.zsh
    - d_astronvim_user
    - f_zshenv
    - f_aliases
