config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_ideavimrc:
    src: ideavimrc
    dst: ~/.ideavimrc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  d_latte:
    src: config/latte
    dst: ~/.config/latte
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  f_p10k.zsh:
    src: p10k.zsh
    dst: ~/.p10k.zsh
  f_aliases.zsh:
    src: oh-my-zsh/custom/aliases.zsh
    dst: ~/.oh-my-zsh/custom/aliases.zsh
  d_i3:
    src: config/i3
    dst: ~/.config/i3
  d_fusuma:
    src: config/fusuma
    dst: ~/.config/fusuma
profiles:
  manjarog:
    dotfiles:
    - f_bashrc
    - f_zshrc
    - f_vimrc
    - f_ideavimrc
    - f_gitconfig
    - d_latte
    - d_alacritty
    - f_p10k.zsh
    - f_aliases.zsh
    - d_i3
    - d_fusuma
