config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
profiles:
  manjarog:
    dotfiles:
    - f_bashrc
    - f_zshrc
    - f_vimrc
