config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_ideavimrc:
    src: ideavimrc
    dst: ~/.ideavimrc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_alacritty.yml:
    src: config/alacritty/alacritty.yml
    dst: ~/.config/alacritty/alacritty.yml
  f_alacritty.sample.yml:
    src: config/alacritty/alacritty.sample.yml
    dst: ~/.config/alacritty/alacritty.sample.yml
  f_p10k.zsh:
    src: p10k.zsh
    dst: ~/.p10k.zsh
  f_aliases.zsh:
    src: oh-my-zsh/custom/aliases.zsh
    dst: ~/.oh-my-zsh/custom/aliases.zsh
  f__a5r:
    src: oh-my-zsh/custom/plugins/a5r/_a5r
    dst: ~/.oh-my-zsh/custom/plugins/a5r/_a5r
  f_config:
    src: config/i3/config
    dst: ~/.config/i3/config
  f_config.yml:
    src: config/fusuma/config.yml
    dst: ~/.config/fusuma/config.yml
  f_init.vim:
    src: config/nvim/init.vim
    dst: ~/.config/nvim/init.vim
  f_face:
    src: face
    dst: ~/.face
profiles:
  manjarog:
    dotfiles:
    - f_bashrc
    - f_zshrc
    - f_vimrc
    - f_ideavimrc
    - f_gitconfig
    - f_alacritty.yml
    - f_alacritty.sample.yml
    - f_p10k.zsh
    - f_aliases.zsh
    - f__a5r
    - f_config
    - f_config.yml
    - f_init.vim
    - f_face
