config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_ideavimrc:
    src: ideavimrc
    dst: ~/.ideavimrc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  d_latte:
    src: config/latte
    dst: ~/.config/latte
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  f_p10k.zsh:
    src: p10k.zsh
    dst: ~/.p10k.zsh
  f_aliases.zsh:
    src: oh-my-zsh/custom/aliases.zsh
    dst: ~/.oh-my-zsh/custom/aliases.zsh
  d_fusuma:
    src: config/fusuma
    dst: ~/.config/fusuma
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_face:
    src: face
    dst: ~/.face
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_aliases:
    src: aliases
    dst: ~/.aliases
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  f_config:
    src: config/i3/config
    dst: ~/.config/i3/config
  f_tmux.conf.local:
    src: tmux.conf.local
    dst: ~/.tmux.conf.local
profiles:
  manjarog:
    dotfiles:
    - f_bashrc
    - f_zshrc
    - f_vimrc
    - f_ideavimrc
    - f_gitconfig
    - d_latte
    - d_alacritty
    - f_p10k.zsh
    - f_aliases.zsh
    - d_fusuma
    - d_nvim
    - f_face
    - f_zshenv
    - f_aliases
    - d_kitty
    - f_config
    - f_tmux.conf.local
