import = ["/home/deep/.config/alacritty/themes/catppuccin-mocha.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
shape = "Block"

[font]
builtin_box_drawing = true
size = 9

[font.normal]
family = "FiraCode Nerd Font"

[[keyboard.bindings]]
action = "ClearHistory"
key = "L"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Z"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[mouse]
hide_when_typing = true

[window]
dynamic_padding = true
opacity = 0.9

[window.dimensions]
columns = 100
lines = 25

[window.padding]
x = 0
y = 0
