import:
  # uncomment the flavour you want below:
  # - ~/.config/alacritty/themes/monokai-soda.yml
  # - ~/.config/alacritty/themes/gruvbox-material.yml
  # - ~/.config/alacritty/themes/gruvbox.yml
  # - ~/.config/alacritty/themes/catppuccin.yml
  - ~/.config/alacritty/themes/catppuccin-mocha.yml
  # - ~/.config/alacritty/themes/tokyo-night.yml
  # - ~/.config/alacritty/themes/schemes.yml

# env:
  # TERM env customization.
  #
  # If this property is not set, alacritty will set it to xterm-256color.
  #
  # Note that some xterm terminfo databases don't declare support for italics.
  # You can verify this by checking for the presence of `smso` and `sitm` in
  # `infocmp xterm-256color`.
  # TERM: xterm-256color

# Window
window:
  dimensions:
    columns: 100
    lines: 25

  padding:
    x: 0
    y: 0

  dynamic_padding: true
  # decorations: none
  opacity: 0.9
  
# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: true

# Font Configuration
font:
  size: 9
  builtin_box_drawing: true
  draw_bold_text_with_bright_colors: true
  normal:
    family: FiraCode Nerd Font
    # family: JetBrainsMono Nerd Font
    # family: Hack Nerd Font
    # family: MesloLGS Nerd Font
    # family: MesloLGSDZ Nerd Font
    # family: MesloLGM Nerd Font
    # style: Regular

# Cursor Config
cursor:
  style:
    shape: Block

# Mouse
mouse:
  hide_when_typing: true
  #url:
  #modifiers: Control

  # Background opacity
  #
  # Window opacity as a floating point number from `0.0` to `1.0`.
  # The value `0.0` is completely transparent and `1.0` is opaque.
  # background_opacity: 0.97

  # Key bindings
key_bindings:
  - { key: L, mods: Control|Shift, action: ClearHistory }
  - { key: Q, mods: Control|Shift, action: Quit }
  - { key: Z, mods: Control|Shift, action: ToggleFullscreen }

  - { key: Equals, mods: Control, action: ResetFontSize }
  - {
      key: NumpadAdd,
      mods: Control|Shift,
      action: IncreaseFontSize
    }
  - {
      key: NumpadSubtract,
      mods: Control,
      action: DecreaseFontSize
    }

  - { key: V, mods: Control|Shift, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: Return, mods: Shift, chars: "\e[13;2u" }
  - { key: Return, mods: Control, chars: "\e[13;5u" }
